---
title: "Final Project"
author: "Matt"
date: "1/31/2019"
output: 
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE)
```

Your final project is due during the 3rd week of May (final exam period).

## Final Project: A tutorial on how to do X in R

For your final project you will create a tutorial about how to something in R. The final project gives you a chance to pursue any topic in the R universe and learn more about it. For example, you could choose to write a tutorial on any R package. If you are interested in solving particular kind of problems, you could write a tutorial on solving those kinds of problems. 

## Topic approval

Have your topic approved with Matt by the end of Spring break.

## Part 1: Give a 5 minute presentation

As a part of your tutorial, you will give a 5 minute presentation to the class summarizing the tutorial. You will use the `xaringan` package to create your slide decks (powerpoint slides), and we devote one class after spring break to show you how to use xaringan.

## Part 2: Write a tutorial

The main part of the final project will be fo you to write a tutorial exploring how to do X in R. You will write an .Rmd file, that explains the issue, and gives example code showing how to solve the issue, or approach the issue. The process of writing a tutorial is a great way to learn the issues at hand yourself. 

All of the tutorials will then be compiled together in a web-book using the `bookdown` package (another class after spring break.)

I expect the tutorial to be comprehensive enough to demonstrate that you have delved into the topic. The length of the tutorial should be consistent with the length of a final paper in a typical content course. 



