
# "psych" Package

## Procedures for Psychological, Psychometric, and Personality Research

## Introduction

Package “psych” is considered an all-purpose toolbox, used for psychometric theory experimental psychology and study of 
personality theory. Several of the “psych” functions are provided to support a book on psychometric theory as well as 

publications in personality research. “psych” package includes a multitude of functions. The package is predominantly 

used for multivariate analysis and scale construction utilizing factor analysis, principle component analysis, cluster 

analysis and reliability analysis. The package also run basic descriptive statistics. It also contains statistics for 

between as well as within group statistics and can analyze the data at multiple levels, including factor analysis and 

correlations. One of many useful functions included in the package is a function for simulating and testing particular 

item and test structures. Several functions serve as a useful front end for structural equation modeling. The package 

also includes graphical displays of path diagrams, factor analysis and structural equation models are created using 

basic graphics. For more information, see the <https://personalityproject.org/r> web page

## Functions for generating simulated data

There are numerous functions included in the package for the sole purpose of generating simulated data. The package 

includes the following functions:


sim The basic simulation functions 

sim.anova  Used to generate 3 independent variables and 1 or more dependent variables for demonstrating ANOVA and lm designs 

sim.circ Generate a two dimensional circumplex item structure 

sim.item Generate a two dimensional simple structure with particular item characteristics 

sim.congeneric Generate a one factor congeneric reliability structure 

sim.minor Simulate nfact major and nvar/2 minor factors 

sim.structural Generate a multifactorial structural model 

sim.irt Generate data for a 1, 2, 3 or 4 parameter logistic model 

sim.VSS Generate simulated data for the factor model 

phi.demo Create artificial data matrices for teaching purposes 

sim.hierarchical Generate simulated correlation matrices with hierarchical or any structure 

sim.spherical Generate three dimensional spherical data (generalization of circumplex to 3 space)


When teaching or studying basic statistics it is very beneficial to Simulate a 3 way balanced ANOVA or linear model, 

with or without repeated measures. Description For teaching basic statistics, it is useful to be capable of generating 

various illustrations fitting for analysis of variance or simple linear models. A function sim.anova, which enables one 
to simulate a 3-way ANOVA or linear model, either with repeated measures or without repeated measures. What sim.anova 

will be able to do is to generate the design matrix that includes three independent variables (IV1, IV2, IV3). The 

independent variables can include any random number of levels and effect sizes for each main effect and interaction. 

Independent variables can be specified as either continuous or categorical as well as have linear or quadratic effects. 

Using a specified model, one can generate either a single dependent variable or multiple (within subject) dependent 

variables. “The repeated measures are assumed to be tau equivalent with a specified reliability.”


### Example of Usage 

sim.anova(es1 = 0, es2 = 0, es3 = 0, es12 = 0, es13 = 0, es23 = 0, es123 = 0, es11=0,es22=0, es33=0,n = 2,n1 = 2, n2 = 

2, n3 = 2, within=NULL,r=.8,factors=TRUE,center = TRUE,std=TRUE)

In the above example the arguments are as follows:

es1 - Effect size of IV1 

es2 -  Effect size of IV2 

es3 - Effect size of IV3 

es12 - Effect size of the IV1 x IV2 interaction 

es13 - Effect size of the IV1 x IV3 interaction 

es23 - Effect size of the IV2 x IV3 interaction 

es123 - Effect size of the IV1 x IV2 * IV3 interaction 

es11 - Effect size of the quadratric term of IV1 

es22 - Effect size of the quadratric term of IV2 

es33 - Effect size of the quadratric term of IV3 

n - Sample size per cell (if all variables are categorical) or (if at least one variable is continuous), the total 

sample size 

n1 - Number of levels of IV1 (0) if continuous 

n2 - Number of levels of IV2 

n3 - Number of levels of IV3 within if not NULL, then within should be a vector of the means of any repeated measures. 

r - the correlation between the repeated measures (if they exist). This can be thought of as the reliability of the 

measures. 

factors - report the IVs as factors rather than numeric 

center - center=TRUE provides orthogonal contrasts, center=FALSE adds the minimum value + 1 to all contrasts 

std - Standardize the effect sizes by standardizing the IVs


###  Details 

The function is used to generate a simple simulation for teaching about ANOVA, regression and reliability. A variety of 
demonstrations of the relation between anova and lm can be generated. 

The function’s default is to generate categorical IVs (factors). When using more than two levels of an IV, it will show 
the difference between the linear model and anova in terms of the comparisons made. 

The within vector can be used to add related equivalent dependent variables. These will have intercorrelations 

(reliabilities) of r and means as specified as values of within. 

To establish the effect of centered versus non-centering, make factors = center=FALSE. The default is to center the 

IVs. The lower order effects will be incorrect given the higher order interaction terms if you will not center the 

IV’s.


Value 

y.df is a data.frame of the 3 IV values as well as the DV values. 

IV1 ... IV3 – are independent variables from 1 ... 3 

DV - If there is a single dependent variable 

DV.1 ... DV.n - If you are specifying within, then the n within subject dependent variables

See also a general set of simulation functions in the psych package sim


### Let’s look at an example of simulated data below

First load the package “psych” through library() if you have not done so

```
set.seed(42) data.df <- sim.anova(es1=1,es2=.5,es13=1) # this piece of code is designed for one main effect and one 

interaction 

describe(data.df) pairs.panels(data.df) #show how the design variables are orthogonal 

# 
summary(lm(DV~IV1*IV2*IV3,data=data.df)) 

summary(aov(DV~IV1*IV2*IV3,data=data.df)) 

set.seed(42) 

# here we are demonstrating the effect of not centering the data on the regression 

data.df <- sim.anova(es1=1,es2=.5,es13=1,center=FALSE) # describe(data.df) 

# 

#this example is not correct, because the IVs are not centered summary(lm(DV~IV1*IV2*IV3,data=data.df)) 

summary(aov(DV~IV1*IV2*IV3,data=data.df)) #compare with the lm model 

#now inspect multiple levels and quadratic terms 

set.seed(42) 

data.df <- sim.anova(es1=1,es13=1,n2=3,n3=4,es22=1) 

summary(lm(DV~IV1*IV2*IV3,data=data.df)) 

summary(aov(DV~IV1*IV2*IV3,data=data.df)) 

pairs.panels(data.df) 

# 

data.df <- sim.anova(es1=1,es2=-.5,within=c(-1,0,1),n=10) pairs.panels(data.df)

```
## Citations

J. Cohen (1982) Set correlation as a general multivariate data-analytic method. Multivariate Behavioral Research, 17(3):301-341.

J. Cohen, P. Cohen, S.G. West, and L.S. Aiken. (2003) Applied multiple regression/correlation analysis for the behavioral sciences. L. Erlbaum Associates, Mahwah, N.J., 3rd ed edition.

H. Hotelling. (1936) Relations between two sets of variates. Biometrika 28(3/4):321-377. E.Cramer and W. A. Nicewander (1979) Some symmetric, invariant measures of multivariate association. Psychometrika, 44:43-54.

V. D. R. Guide Jr. and M. Ketokivim (2015) Notes from the Editors: Redefining some methodological criteria for the journal. Journal of Operations Management. 37. v-viii




